import_from_git(url: 'https://github.com/jacobvanorder/FastlaneIssueImportedFastlane.git')

platform :ios do
  before_all do |lane, options|
  end

  after_all do |lane, options|
    if lane == :test
      puts "Main Fastfile: Ran build from Fastfile"
    elsif lane == :child_test
      puts "Main Fastfile: Ran child_build from Fastfile"
    end
  end

  error do |lane, exception|
    puts "Main Fastfile: #{exception} on lane: #{lane}"
  end

  desc "Runs Scan"
  lane :test do |options|
    child_test
  end
end
